### PR TITLE
Adding Bootstrap login page

### PR DESCRIPTION
**Pull request by denics**
This add a bootstrap compliant login page. Registration and Password reset to come!

### CODE REVIEW

**Comment by denics** [comment]
This is the resulting page

screen shot 2015-08-05 at 16 01 05

**Comment by thalitar** [comment]
Hi Denic, you are okay? 
I want use a search bar in the homepage in my eprints repository, a search bar same yours in the example, but i have no idea how to do this. You can help me?
gatinho

**Comment by davidmce** [comment]
Looks good. I've not got a box to try all this out on but hopefully get sorted out soon and get back on it.

**Comment by denics** [comment]
Hi @thalitar , as soon as I have finish with the code and the thing published, I will add all my files here as example.

**Pull request merged**
